### PR TITLE
Fixes/tests for empty targets and cleanup

### LINKED ISSUE #222: poor error message for empty string input
While playing with `matgeom`'s maintainer makefile, I hit the following:
```
Doctest v0.7.0: this is Free Software without warranty, see source.

error: what(1): out of bound 0 (note: variable 'what' shadows function)
make: *** [Makefile:165: doctest] Error 1
```

1. I think probably the input list was empty but we should have a better error message in that case.  In fact, I can reproduce this:

```
>>> doctest('')
Doctest v0.7.0: this is Free Software without warranty, see source.

error: what(1): out of bound 0 (note: variable 'what' shadows function)
error: called from
    doctest_collect at line 40 column 3
    doctest at line 349 column 11
```

2. We shouldn't use `what` as a variable name if that shadows something.

### PR DESCRIPTION
**Pull request by cbm755**
Fixes #222.

### CODE REVIEW

File: inst/private/doctest_collect.m [hunk 1]
```diff
@@ -19,16 +19,20 @@
 % TODO: methods('logical') octave/matlab differ: which behaviour do we want?
 % TODO: what about builtin "test" versus dir "test/"?  Do we prefer dir?
 
+if (isempty(w))
+  return
+end
+
```
Comment (cbm755) [inline inst/private/doctest_collect.m]: This PR may look invasive but this is the only functional change.
